"""empty message

Revision ID: 7630095da6d1
Revises: 2a7fbf3116bd
Create Date: 2018-08-18 17:20:40.858184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7630095da6d1'
down_revision = '2a7fbf3116bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('UC_user_id_group_id', 'members', ['user_id', 'group_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('UC_user_id_group_id', 'members', type_='unique')
    # ### end Alembic commands ###
